class X12Labels:
    """X12 Segment and Element Labels/Descriptions"""

    # Segment descriptions - Claim Adjustment Reason Codes (CARC)
    REASON_MAP = {
        "1": "Deductible amount",
        "2": "Coinsurance amount",
        "3": "Co-payment amount",
        "4": "The procedure code is inconsistent with the modifier used",
        "5": "The procedure code is inconsistent with the place of service",
        "6": "The procedure/revenue code is inconsistent with the patient's age",
        "7": "The procedure/revenue code is inconsistent with the patient's gender",
        "8": "The procedure code is inconsistent with the provider type/specialty",
        "9": "The diagnosis is inconsistent with the patient's age",
        "10": "The diagnosis is inconsistent with the patient gender",
        "11": "Diagnosis inconsistent with procedure",
        "12": "The diagnosis is inconsistent with the provider type/specialty",
        "13": "The benefit maximum for this time period or occurrence has been reached",
        "14": "The benefit maximum for this service has been reached",
        "15": "The authorization number is missing, invalid, or does not apply",
        "16": "Claim/service lacks information or has submission/billing error",
        "17": "Requested information could not be obtained",
        "18": "Duplicate claim/service",
        "19": "Claim/service not covered by this payer/contractor",
        "20": "The payer has determined the submitted documentation does not support this level of service",
        "21": "Payment adjusted because the patient is covered under a primary plan",
        "22": "This care may be covered by another payer per coordination of benefits",
        "23": "Claim denied due to lack of prior authorization/precertification",
        "24": "Capitation payment is for services not covered under the plan",
        "25": "Payment denied. Your stop loss deductible has not been met",
        "26": "Expenses incurred prior to coverage",
        "27": "Expenses incurred after coverage terminated",
        "28": "Coverage not in effect at the time the service was provided",
        "29": "Time limit for filing has expired",
        "30": "Payment adjusted because the patient has not met the required eligibility requirements",
        "31": "Patient cannot be identified as our insured",
        "32": "Our records indicate patient is not enrolled at time of service",
        "33": "Insured has no dependent coverage",
        "34": "Insured has no coverage for newborns",
        "35": "Lifetime benefit maximum has been reached",
        "36": "Balance does not exceed co-payment amount",
        "37": "Balance does not exceed deductible",
        "38": "Services not provided or authorized by designated/treating provider",
        "39": "Services denied at the time authorization was requested",
        "40": "Charges do not meet qualifications for emergency/urgent care",
        "41": "Discount agreed to in preferred provider contract",
        "42": "Charges exceed our fee schedule or maximum allowable amount",
        "43": "Gramm-Rudman reduction",
        "44": "Prompt-pay discount",
        "45": "Charge exceeds fee schedule allowed amount",
        "46": "This service/procedure has not been deemed medically necessary",
        "47": "This is not covered with this procedure combination",
        "48": "This is not covered with this diagnosis",
        "49": "These are non-covered services because this is a routine exam",
        "50": "These are non-covered services",
        "51": "These are non-covered services because this is a pre-existing condition",
        "52": "The referring/prescribing/rendering provider is not eligible to refer/prescribe/order/perform the service billed",
        "53": "Services by this provider are not covered",
        "54": "Services billed are not payable under the plan",
        "55": "Claim/service not covered under this provider contract",
        "56": "Procedure/service not allowed due to plan limitations",
        "57": "Payment denied/reduced. Certification is not required for this service",
        "58": "Claim/service denied because procedure/service was not medically necessary",
        "59": "Processed based on multiple/duplicate procedure rule",
        "60": "Charges for outpatient services are not covered when inpatient",
        "61": "Bundled services — cannot be billed separately",
        "62": "Claim/service denied — missing/invalid diagnosis or procedure code",
        "63": "Claim/service denied — invalid date of service",
        "64": "Claim/service denied — invalid place of service",
        "65": "Claim/service denied — invalid provider specialty",
        "66": "Blood deductible not met",
        "67": "Claim/service denied — invalid or missing procedure modifier",
        "68": "Claim/service denied — missing or invalid referring provider information",
        "69": "No benefit coverage for this type of service",
        "70": "Payment adjusted — payment included in allowance for another service",
        "71": "Payment adjusted — payment included in global surgical package",
        "72": "Payment adjusted — services not separated",
        "73": "Payment adjusted — incidental procedure",
        "74": "Corrected claim — charges already considered in previous adjudication",
        "75": "Payment adjusted — overlapping procedure",
        "76": "Provider not eligible to bill this service",
        "77": "Service not provided during benefit period",
        "78": "Cost outlier — payment adjustment",
        "79": "Non-covered durable medical equipment",
        "80": "Non-covered visits",
        "81": "Non-covered days",
        "82": "Provider not contracted / not eligible to perform this service",
        "83": "No appeal rights. Adjudicative decision based on the provisions of a demonstration project",
        "84": "Patient has excess coverage",
        "85": "Patient is a member of a group participating in a demonstration project",
        "86": "Service denied because maximum stay has been reached",
        "87": "Transfer from an acute care hospital. Payment based on this plan's transfer policy",
        "88": "Claim/service denied based on payer's decision regarding transfer of care",
        "89": "Services not provided or authorized by designated/treating provider",
        "90": "Service or supply was subject to sales tax",
        "91": "Deferred to entity that has responsibility for review of the claim",
        "92": "Claim denied for requesting information; review was originally deferred to another payer",
        "93": "No longer eligible for coverage due to end stage renal disease",
        "94": "Processed in accordance with Fair Debt Collection Practices Act requirements",
        "95": "Plan procedures not followed",
        "96": "Non-covered charge(s)",
        "97": "Payment is included in another billed procedure (bundled service)",
        "98": "Procedure/benefit is not covered",
        "99": "Service denied. This payer does not cover this service when performed on the same day as another covered service for the same patient",
        "100": "Payment made to the patient/insured",
        "101": "Non-covered days/room charge",
        "102": "Major medical adjustment",
        "103": "Provider promotional discount (e.g., Senior citizen discount)",
        "104": "Claim/service subject to deductible or co-pay",
        "105": "Service paid by another payer",
        "106": "Prior payment being corrected",
        "107": "Processed according to contract provisions",
        "108": "Rent/purchase guidelines were not met",
        "109": "Claim not covered because provider was not certified/licensed",
        "110": "Claim/service not covered by this payer/contractor",
        "111": "Not covered unless the service is emergency care",
        "112": "Service rendered in unauthorized location",
        "113": "Authorization/certification/notification not obtained",
        "114": "Claim/service denied based on utilization review",
        "115": "Claim/service denied based on provider contracting/credentialing",
        "116": "Patient or authorized representative did not execute the required advance directive forms",
        "117": "Claim/service missing required supportive documentation",
        "118": "Charges for services rendered are not covered under the member's contract",
        "119": "Benefit maximum for this time period or occurrence has been reached",
        "120": "Patient is covered by another payer/has exhausted Medicare benefits",
        "121": "Indicated billed services are inconsistent with related claim",
        "122": "Psychiatric reduction",
        "123": "Additional information requested from entity",
        "124": "Processed based on ancillary or outpatient services",
        "125": "Submission/billing error",
        "126": "Deductible or coinsurance waived",
        "127": "Invalid or missing patient/member ID",
        "128": "Newborn's services are included in the mother's bill",
        "129": "Documentation submitted does not support billed service",
        "130": "Payment reduced when performed by this type of provider in this type of facility",
        "131": "Claim submitted to incorrect payer/contractor",
        "132": "Adjustment to the prevailing wage index",
        "133": "Prearranged demonstration project adjustment",
        "134": "Technical component converted to professional component",
        "135": "Claim denied — level of care not supported",
        "136": "Total reimbursement for services rendered during this admission that were related to the surgical procedure",
        "137": "Payment based on Regulatory Mandated/Legislated Fee Schedule for this service",
        "138": "Appeal rights not exhausted or improper filing",
        "139": "Contracted funding agreement — transplant seeking non-network services outside of patient's home state",
        "140": "Patient is enrolled in hospice — service not allowed",
        "141": "Claim spans eligible and ineligible period of coverage",
        "142": "Monthly capitation payment",
        "143": "Portion of payment deferred",
        "144": "Payment reduced as a result of therapy protocols",
        "145": "Portion of payment subject to patient's spend down",
        "146": "Diagnosis was invalid for the date(s) of service",
        "147": "Provider contracted/negotiated rate expired or not on file",
        "148": "Claim/service span must be 30 days or less",
        "149": "Payment adjusted based on per diem or cost containment program",
        "150": "Provider not contracted for this type of service",
        "151": "Payment adjusted because service is part of case rate/package",
        "152": "Payment adjusted because service is part of DRG/capitation",
        "153": "Service not payable due to medical necessity criteria",
        "154": "Service requires referral",
        "155": "Payment based on payment after subrogation from third party payer",
        "156": "Service already separately reimbursed",
        "157": "Service provided as a result of an act of war",
        "158": "Service is excluded under the national drug code",
        "159": "Service rendered in excluded facility",
        "160": "Injury/illness covered by insurance which does not qualify",
        "161": "Provider/supplier performance bonus",
        "162": "State-mandated requirement for mental health parity",
        "163": "Attachment referenced on the claim was not received",
        "164": "Attachment referenced on the claim was not received in a timely fashion",
        "165": "Referral missing or invalid",
        "166": "These services were submitted after this payer's filing limit",
        "167": "This provider was not certified/eligible for this service in this location on this date of service",
        "168": "Service provided by an excluded provider",
        "169": "Bilateral procedures are not allowed",
        "170": "Payment denied when performed by this type of provider",
        "171": "Payment denied due to provider type and facility mismatch",
        "172": "Payment adjusted based on use of out-of-network pharmacy",
        "173": "Service was not prescribed by a physician",
        "174": "Service was not prescribed before delivery",
        "175": "Prescription does not conform with plan benefit limits",
        "176": "Prescription does not include required clinical information",
        "177": "Patient has not met the required eligibility requirements",
        "178": "Claim/service not covered by this payer/contractor. Additional information needed from entity",
        "179": "Claim/service not covered. Patient is currently participating in a clinical trial",
        "180": "Patient is not currently enrolled in this plan",
        "181": "Procedure denied. Consent form required for this procedure is not on file",
        "182": "Procedure denied. Home health service plan not on file",
        "183": "Procedure denied. Attending physician not on staff of this facility",
        "184": "Patient not eligible on the date of service",
        "185": "Claim/service denied. Patient has not met required waiting period",
        "186": "Level of care change adjustment",
        "187": "Consumer-directed option does not permit coverage of this service",
        "188": "Claim/service denied. Patient is covered by another payer",
        "189": "Not otherwise classified or unlisted procedure",
        "190": "Payment denied. Patient is a Medicaid beneficiary",
        "191": "Services not included in the appeal review",
        "192": "Claim denied. Non-standard adjustment code from property and casualty payer",
        "193": "Claim/service denied. Original claim accepted and paid but has since been voided",
        "194": "Anesthesia performed by the operating physician, the assistant surgeon or the attending physician",
        "195": "Refund issued to an erroneous priority payer for this claim/service",
        "196": "Claim/service denied. Patient's coverage terminated at date of service",
        "197": "Precertification/authorization not requested or not obtained",
        "198": "Claim denied. Workers compensation jurisdictional fee schedule adjustment",
        "199": "Revenue code/item not recognized by this payer",
        "200": "Expenses incurred during lapse in coverage",
        "201": "Workers compensation case settled. Patient is responsible for amount of this claim",
        "202": "Non-covered personal comfort or convenience services",
        "203": "Discontinued or reduced service",
        "204": "Service/equipment not covered for this diagnosis",
        "205": "Pharmacy discount card processing fee",
        "206": "National Provider Identifier - missing",
        "207": "National Correct Coding Initiative (NCCI) denial",
        "208": "Missing/inconsistent date of service or period",
        "209": "Provider exceeded service limits",
        "210": "Service denied due to provider agreement or licensing issues",
        "211": "National Provider Identifier - invalid format",
        "212": "National Provider Identifier - not matched to a valid entity",
        "213": "National Provider Identifier - missing when required",
        "214": "Workers compensation claim adjudicated as non-covered. Forwarded to patient's health plan",
        "215": "Based on subrogation of a third party settlement",
        "216": "Legislative Fee Schedule penalty",
        "217": "Managed care withhold",
        "218": "Exact duplicate claim/service",
        "219": "Rebill as separate claim line to resolve",
        "220": "Patient financial responsibilities related to a disproportionate share hospital payment",
        "221": "Workers compensation offset",
        "222": "Exceeds the contracted maximum number of hours/days/units",
        "223": "Adjustment code for mandated federal, state or local law/regulation",
        "224": "Patient rate adjustment",
        "225": "Penalty for failure to obtain second surgical opinion",
        "226": "Information requested from the billing/rendering provider",
        "227": "Information requested from the patient/insured/responsible party",
        "228": "Denied for failure of this provider to submit requested information in a timely manner to the payer",
        "229": "Partial charge amount not considered by payer",
        "230": "Claim/service not covered - cosmetic",
        "231": "Mutually exclusive procedures cannot be done in the same day/setting",
        "232": "Claim/service not considered by payer when rendered by this provider type in this type of facility",
        "233": "Claim overlaps inpatient stay",
        "234": "This procedure is not paid separately",
        "235": "Sales tax",
        "236": "Legislative rollbacks or other legislative changes",
        "237": "Legislatively mandated payer fee",
        "238": "Claim spans eligible and ineligible period of coverage. Rebill separate claims",
        "239": "Claim spans multiple months. Rebill separate claims",
        "240": "The diagnosis is inconsistent with the patient's birth weight",
        "241": "Low birth weight adjustment",
        "242": "Automatic medical records penalty",
        "243": "Unrelated service by a provider during a global period",
        "244": "Payment reduced/denied because the service was provided as part of a clinical trial",
        "245": "Provider performance program withhold",
        "246": "This non-payable code is for required reporting only",
        "247": "Deductible for professional service rendered by a facility provider billing on a professional claim",
        "248": "Coinsurance for professional service rendered by a facility provider billing on a professional claim",
        "249": "This claim has been identified as a readmission. Reimbursement for this admission was included with the payment for the initial admission",
        "250": "Claim was not processed in a timely manner. Payment/denial is due to a payment demonstration program",
        "251": "The attachment claim is denied. To have the service(s) considered for payment, the services must be submitted on a standard claim form",
        "252": "An attachment/other documentation is required to adjudicate this claim",
        "253": "Sequestration - reduction in federal payment",
        "254": "Claim/service denied. Additional information needed for secondary/tertiary payer",
        "255": "Claim/service denied. Procedure code billed exceeds contracted facility type maximum",
        "256": "Service not payable per managed care contract",
        "257": "Services denied as related to an auto accident—submit to auto insurer",
        "258": "Service denied as related to workers compensation",
        "259": "Additional payment for Distinct Medical Visit",
        "260": "Processed under Medicaid ACA Enhanced Fee Schedule",
        "261": "Claim denied for not meeting timely filing requirements",
        "262": "Adjustment for delivery cost. Future purchase of service(s) or supply should be obtained from approved source",
        "263": "Adjustment for delivery cost. Delivery method should be modified for future services",
        "264": "Patient's condition was caused by a precipitating event which cannot be covered under health insurance",
        "265": "Adjustment for therapy protocols not followed",
        "266": "Payment adjusted. This service is paid only once per patient lifetime",
        "267": "Claim/service denied. This service was provided during pre-operative or post-operative period",
        "268": "Claim/service denied. Patient did not meet eligibility requirements based on provider type and contract",
        "269": "Anesthesia not covered for this service/procedure",
        "270": "Claim/service denied. Patient medical record does not support billed service",
        "271": "Prior contractual reductions related to a demonstration project",
        "272": "Coverage/program guidelines were not met",
        "273": "Coverage/program guidelines were exceeded",
        "274": "Fee/Service not payable per patient Care Coordination arrangement",
        "275": "Prior payer's (or payers') patient responsibility (deductible, coinsurance, copayment) not covered",
        "276": "Services denied by the prior payer(s) are not covered by this payer",
        "277": "The disposition of the related Property & Casualty claim (injury or illness) is pending due to litigation",
        "278": "Submission/billing error(s). Claim must be resubmitted with corrected information",
        "279": "Services not covered due to a previous bankruptcy filing",
        "280": "Claim/service denied. Claim must be resubmitted as corrected claim",
        "281": "Deductible waived per contractual/regulatory requirement",
        "282": "Payment adjusted to reflect rebate allocated to payer by manufacturer",
        "283": "Attending or facility fee reduction",
        "284": "Claim/service(s) subject to appeal and/or reconsideration process",
        "285": "Appeal/reconsideration received. Claim/service reviewed and related to additional payment issued",
        "286": "Appeal/reconsideration received. Claim/service reviewed but no additional payment issued",
        "287": "Claim transferred to proper payer/processor",
        "288": "Claim/service not covered. Consult plan benefit documents/guidelines for information about restrictions for this service",
        "289": "Services not included because coverage is limited to specific licensed/certified providers",
        "290": "Services not included because coverage is limited to providers with specific training or expertise",
        "291": "Patient is covered by the family policy. Payment has been made to the parent policy",
        "292": "Payment reduced for failure to properly disclose to the payer on a claim the patient's inpatient status",
        "293": "Reduced/denied for failure of claim preparer or authorized representative to provide sufficient documentation to support the complexity of evaluation and management services rendered",
        "294": "Claim/service denied. Patient care was not the responsibility of the subscriber per the separation agreement",
        "295": "Claim/service denied. Patient is enrolled in a Medicare Advantage demonstration project. This should be submitted to Medicare Advantage plan",
        "296": "Services not reimbursable under patient's benefit plan",
        "297": "The performed procedure has been converted to one requiring less resources",
        "298": "Reduced/denied for failure to obtain prior authorization",
        "299": "Reduced/denied for failure to report other insurance coverage on initial claim submission",
        "300": "Reduced/denied for failure to properly report the insured's certificate/identification number",
        "301": "Claim/service denied. Patient signature on file does not match signature on this claim",
        "302": "Claim/service denied. This payer is the third party administrator. Services were denied due to limitations and/or restrictions of the plan benefit",
        "303": "Claim/service denied. The payer's coverage is secondary to a patient's worker's compensation benefits",
        "304": "Reduced/denied for failure to obtain or provide a valid prior authorization number",
        "305": "Claim/service denied. Out-of-network pharmacy not used",
        "306": "Claim/service not covered. Consult plan benefit documents/guidelines for information about specific restrictions",
        "307": "Claim/service not covered. Non-formulary drug not authorized",
        "308": "Claim/service not covered. Quantity exceeds the plan limitations",
        "309": "Service not payable because billed on wrong claim form type",
        "310": "Payment adjusted based on contracted discount percent",
        "311": "Prompt payment discount",
        "312": "Service denied. Patient is not the primary dependent",
        "313": "Services not covered. Patient not eligible based on coverage effective date",
        "314": "Claim/service not covered. Patient not eligible based on coverage termination date",
        "315": "Claim/service denied. The authorization used on this claim was not obtained through the proper channels",
        "316": "Medicare Advantage fee schedule used",
        "317": "Claim/service not covered. Prior Authorization Request was denied",
        "318": "Claim/service denied. Non-plan specific pharmacy not used",
        "319": "Claim/service not covered. The day supply for medication dispensed does not match the plan's requirements",
        "320": "Claim/service not covered. The dosage of medication dispensed does not match the dosage specified on the prescription",
        "321": "Claim/service not covered. Patient is covered by a Medicare Advantage HMO/POS plan",
        "322": "Claim/service not covered. Patient's gender, age or condition does not meet plan eligibility requirements",
        "323": "Reduced/denied for failure to obtain documentation/evidence of medical necessity",
        "324": "Reduced/denied for failure of this provider to notify the payer within the plan's required timeframe",
        "325": "Claim/service denied. Services by this provider are only covered with prior authorization",
        "326": "Reduced/denied for failure to obtain pre-admission review/certification",
        "327": "Claim/service denied. This service is allowed only in specific circumstances or settings",
        "328": "Claim/service denied. Patient is enrolled in a Medicare program",
        "329": "Claim/service not covered. Patient did not pay provider",
        "330": "Claim/service not covered. Patient is on a trial basis. Services are subject to review",
        "331": "Claim/service denied. Services rendered at a location not covered under contract",
        "332": "Claim/service denied. Patient is covered by a Medicare Advantage HMO/POS plan outside the network service area",
        "333": "Claim/service denied. Patient did not obtain services from the contracted facility/location",
        "334": "This claim has been identified as a duplicate",
        "335": "Claim denied. Payment already made for same/similar procedure within set time frame",
        "336": "Claim/service denied. Internal policy not met",
        "337": "Claim/service denied. Patient must obtain treatment from a specific approved facility/provider",
        "338": "Claim/service not covered. Services are not covered in the location where services were performed",
        "339": "Services not covered. Services are not covered in the service location indicated",
        "340": "Reduced/denied for failure to perform services on consecutive days per medical guidelines",
        "341": "Claim/service denied. Services delivered outside of approved facility network",
        "342": "Claim/service not covered. This service is not covered when patient's condition is the result of a non-covered condition/service",
        "343": "Services not covered. Services are provided in a facility not covered under the member's benefit plan",
        "344": "Claim/service denied. Patient has active coverage through another payer",
        "345": "This claim/service was processed according to state regulations",
        "346": "Missing documentation required for processing this claim",
        "347": "Claim/service denied. Patient did not receive services at a facility owned by this payer",
        "348": "This service is not paid separately when billed with the same date of service",
        "349": "Claim/service denied. Crossover claim is subject to COB with another payer",
        "350": "Claim/service not covered. Consent form not signed",
        "351": "Reduced/denied for patient's failure to follow prescribed treatment",
        "352": "Claim/service not covered. Treatment was not prescribed",
        "353": "Attending provider does not meet contracting qualifications",
        "354": "Attending provider does not meet plan or network credentialing standards",
        "355": "Reduced/denied because the patient was not certified/eligible at the time the service was performed",
        "356": "Reduced/denied per regulatory requirement",
        "357": "Service denied. Patient failed to complete/return required forms",
        "358": "Services not covered under the patient's current benefit plan",
        "359": "Claim/service not covered. The purchase of product/service was not within time limit specified by plan benefit",
        "360": "Patient must obtain treatment from network provider",
        "361": "Claim/service denied. The patient's diagnosis is not consistent with their prescribed medications",
        "362": "Claim/service not covered. Direct patient payments not allowed by law or program",
        "363": "Claim/service not covered. Paid fully under a previous Medicare secondary payer relationship",
        "364": "Claim/service denied. The patient is enrolled in a Medicare Advantage demonstration project",
        "365": "Service provided in a location that is not covered by this payer",
        "366": "Adjustment to the Drug Cost Unit Price for the reported fee schedule. Drug cost does not include the dispensing fee",
        "367": "Drug not covered. Patient is enrolled in a Medicare Part D program",
        "368": "Reduced/denied because the facility did not meet criteria in accordance with national legislation",
        "369": "Reduced/denied because the service performed does not meet service-specific criteria in accordance with national legislation",
        "370": "Claim/service not covered. Incomplete/Invalid treatment plan",
        "371": "Reduced/denied for missing, incomplete, or invalid authorization",
        "372": "Claim/service not covered. Multiple units billed incorrectly",
        "373": "Claim/service not covered. Service exceeds plan limits",
        "374": "Reduced/denied for missing, incomplete, or invalid service modifier",
        "375": "Claim/service not covered. Pre-treatment review/predetermination not obtained",
        "376": "Adjustment for services provided out-of-sequence",
        "377": "Services that are furnished incident to the professional service of a physician or other healthcare professional are included in the payment for the professional service",
        "378": "Claim/service not covered. Patient is enrolled in a PACE program",
        "379": "Claim/service not covered. Services are not covered under the patient's program type",
        "380": "Patient is enrolled in a Medicaid state demonstration",
        "381": "Services not covered. Services are provided under a PACE program",
        "382": "Claim/service denied. The procedure code billed cannot be paid when the line item date of service is in the range that includes the date of service for a previously adjudicated claim",
        "383": "Claim/service not covered. Services are not covered when performed outside of the plan's geographic service area",
        "384": "Claim/service denied. Therapy cap exceeded",
        "385": "Claim/service not covered. The benefit is available under a Capitation plan",
        "386": "Service not covered. Benefits exhausted",
        "387": "Claim/service not covered. The therapy is for multiple regions which exceeds the plan limit for this type of service",
        "388": "Claim/service denied. Consult plan documents for coverage information",
        "389": "Claim/service denied. The patient is not a valid member of the plan",
        "390": "Claim/service not covered. Patient is currently participating in an early intervention program",
        "391": "Claim/service denied. Coordination of benefits with the primary payer was not completed",
        "392": "Claim/service denied. Consult plan coverage rules to determine eligibility requirements",
        "393": "Claim/service not covered. Patient failed to complete required health assessment",
        "394": "Claim/service not covered. Service must be coordinated through the plan's disease management program",
        "395": "Claim/service not covered. Patient was not properly screened for this service",
        "396": "Claim/service denied. Duplicate service line has been corrected/voided",
        "397": "State-mandated Requirement for Property and Casualty, see claim payment remarks for specific information",
        "398": "Claim/service denied. Services provided are for treatment of a condition covered under the workers compensation fee schedule",
        "399": "Claim/service not covered. Provider does not meet the necessary qualifications to perform this service",
        "400": "Charges for an assistive device are included in the payment for the implant and not paid separately",
        "401": "Claim/service denied. Patient is enrolled in a spend down program",
        "402": "Claim/service denied. This is a supplemental pharmacy benefit and patient must first utilize their primary benefit",
        "403": "Claim/service not covered. Medical record does not support decision",
        "404": "Claim/service denied. Consult plan coverage rules or patient's plan documents regarding payment for this service",
        "405": "Claim/service not covered. The procedure was not ordered by a qualified healthcare professional",
        "406": "Claim/service denied. Patient is enrolled in a Patient Centered Medical Home program",
        "407": "Claim/service not covered. Services provided are for treatment of a condition covered under the federal black lung program",
        "408": "Claim/service not covered. Coordination of benefits with the national workers compensation plan was not completed",
        "409": "Claim/service denied. Prior authorization obtained was for a different service or provider",
        "410": "Payment adjusted to reflect services related to additional therapy units. Consult plan benefit documents/guidelines for information about restrictions for this service",
        "411": "Payment adjusted to reflect pre-approved/authorized units. Consult plan benefit documents/guidelines for information about restrictions for this service",
        "412": "Payment adjusted as this service is subject to patient pay and chase",
        "413": "Reduced/denied for failure to obtain prior authorization for an out-of-network provider",
        "414": "Service not covered. Patient is covered by a Medicare Advantage plan",
        "415": "Payment adjusted based on Maximum Allowable Fee Schedule",
        "416": "Claim/service denied. Consult plan benefit documents for information about this service",
        "417": "Payment adjusted. The level of service has been adjusted because the supporting documentation did not meet the reporting requirements",
        "418": "Claim/service denied. Not qualified for recovery benefits",
        "419": "Claim/service not covered. Preventive services must be provided by an in-network provider",
        "420": "Services not covered. Patient did not receive/seek treatment from a local facility",
        "421": "Services not covered. Patient must first attempt treatment with approved drug regimen",
        "422": "Claim/service not covered. The prescription is covered under a separate prescription drug benefit",
        "423": "Claim/service denied. Medical record must be available for review by the payer or state inspector",
        "424": "Not payable per participating provider agreement",
        "425": "Claim/service denied. The ordering provider does not meet requirements to order this service",
        "426": "Claim/service not covered. Payment included in a previously reported pharmacy dispensing fee",
        "427": "Claim/service denied. Patient must complete required pre-treatment documentation",
        "428": "Reduced/denied because the provider does not meet the required staff requirements",
        "429": "Reduced/denied because the provider does not meet the facility certification requirements",
        "430": "Adjustment code for mandated state, federal or local law/regulation that is not already covered by another code",
        "431": "Plan's maximum retrospective review period exceeded",
        "432": "Services not covered. Patient is in a disenrollment time frame",
        "433": "The Demonstration Project payment exceeds the approved amount. Service subject to reasonable charges on the claim",
        "434": "Payment reduced as ambulatory patient group cap was exceeded",
        "435": "Claim/service denied. Procedures on the same line are duplicates",
        "436": "Claim/service denied. Consult plan benefit documents/guidelines for information about eligibility requirements for this service",
        "437": "Claim/service not covered. The patient's prior payer(s) did not cover the service based on submission errors by the provider or patient",
        "438": "Claim/service denied. The patient is eligible for expedited review",
        "439": "Claim/service not covered. Service is related to the treatment of a pre-existing condition",
        "440": "Charges are applied to the Major Medical Deductible and not paid",
        "441": "Reduced/denied for failure to obtain approval for the order of service from qualified licensed provider",
        "442": "Claim/service denied. Medicare Advantage program guidelines not followed",
        "443": "Claim/service denied. Services by an out-of-network provider are subject to a different cost sharing calculation",
        "444": "Claim/service not covered. Provider must obtain certification/training/re-certification/re-training to provide this service",
        "445": "Reduced/denied for failure to provide supporting itemized bill/statement",
        "446": "Service not performed by covered providers/suppliers",
        "447": "Claim/service not covered. The patient is not enrolled in the plan as a primary member",
        "448": "Claim/service denied. Patient's cost share does not apply. Plan benefit exceeds fee schedule amount",
        "449": "Claim/service not covered. Cost share does not apply to this service. Consult plan benefit documents",
        "450": "Reduced/denied because the insurance company was not notified of this admission as required by this benefit plan",
        "451": "Claim/service not covered. Services not authorized or required by your plan benefit",
        "452": "Reduced/denied because the patient's enrollment was processed in a different system",
        "453": "Claim/service denied. Admitting provider does not meet plan's credentialing standards",
        "454": "Reduced/denied. This payer does not cover patient liability resulting from other payer's payment for this service",
        "455": "Claim/service denied. Patient is enrolled in a medical home",
        "456": "Claim/service not covered. Pre-existing condition waiting period not met",
        "457": "Claim/service not covered. Patient is covered by another dental carrier",
        "458": "Claim/service denied. Patient did not choose a primary care provider",
        "459": "Payment based on demonstration specific pricing",
        "460": "Payment adjusted based on the application of activity-based weights for the episode of care/case",
        "461": "Claim/service denied. Consult plan benefit documents or contact payer for coverage information regarding this service",
        "462": "Payment adjusted to reflect provider selection of alternate service",
        "463": "Services provided in an inappropriate place of service",
        "464": "Claim/service denied. This procedure is not payable for the patient's demographic characteristics",
        "465": "Services provided in an inappropriate facility",
        "466": "Services provided in an inappropriate location",
        "467": "This claim/service was not initiated within the approved timeframe",
        "468": "Payment denied/reduced. Services related to a disproportionate share hospital payment have been added to the patient's financial responsibility",
        "469": "Payment adjusted to reflect charges for services performed by this provider type, submitted by other providers",
        "470": "Reduced/denied for missing, incomplete, or invalid patient liability amount",
        "471": "Reduced/denied for missing, incomplete, or invalid charges for services",
        "472": "Reduced/denied because the drug is self-administered and cannot be covered",
        "473": "Claim/service denied. Documentation submitted was altered and does not support the service",
        "474": "Claim/service not covered. This service is not covered when performed by this provider type/specialty",
        "475": "Payment adjusted because the service is related to the treatment for a service that is bundled",
        "476": "Reduced/denied for incomplete or invalid anesthesia information",
        "477": "Claim/service not covered. Consent on file does not match requirements for this service",
        "478": "Reduced/denied for missing, incomplete, or invalid prescribing provider identifier",
        "479": "Claim/service denied. Patient did not meet eligibility requirements. The patient's enrollment was not renewed or processed",
        "480": "Claim/service not covered. Your Health Plan is secondary to the federal black lung program",
        "481": "Claim/service not covered. Patient has reached maximum out-of-pocket amount",
        "482": "Payment adjusted to the reduced rate for the member's benefit level",
        "483": "Reduced/denied for incomplete, missing, or invalid number of units",
        "484": "Claim/service not covered. The group or employer's coverage has been cancelled",
        "485": "Claim/service denied. Pre-admission review is required",
        "486": "Claim/service denied. Pre-treatment estimate must be obtained from the payer prior to rendering services",
        "487": "Claim/service not covered. Patient is eligible for enhanced benefits",
        "488": "Adjustment code for mandated regulatory assessment by federal, state or local requirement",
        "489": "Reduced/denied for missing, incomplete, or invalid ordering provider's or referring provider's certification or recertification",
        "490": "Reduced/denied for missing, incomplete, or invalid patient weight",
        "491": "Reduced/denied for missing, incomplete, or invalid patient height",
        "492": "Alert: Payment is adjusted when procedure is performed in this place of service based on the facility fee schedule",
        "493": "Reduced/denied for incomplete or invalid information from the supplier",
        "494": "Payment adjusted because this service is bundled with the service billed with a CPT code for temporary procedures/services",
        "495": "Payment adjusted. Claim overlaps multiple periods",
        "496": "Reduced/denied for incomplete or invalid plan information",
        "497": "Reduced/denied for missing, incomplete, or invalid date of last contact with patient",
        "498": "Claim/service not covered. Patient is covered under a previous insurance contract",
        "499": "Claim/service denied. This service was performed during a period when an approved clinical trial was not active or the provider was not authorized to participate in the clinical trial",
        "500": "Reduced/denied for missing, incomplete, or invalid anesthesia conversion factor",
        "501": "Reduced/denied for missing, incomplete, or invalid certification or recertification",
        "502": "Adjustment for a regulatory or business mandate that is not already covered by another code or for which there is not a more specific code",
        "503": "Charges for the services are included in the facility charge/all-inclusive rate/ambulatory surgery facility rate",
        "504": "Claim/service not covered. This service is covered under the Medical or Hospital benefit which has not been exhausted",
        "505": "Claim/service denied. Services must be delivered or provided directly or arranged by plan's designated utilization review contractor",
        "506": "Services not covered based on the patient's classification as a facility patient",
        "507": "Reduced/denied for missing, incomplete, or invalid consent from the patient",
        "508": "Claim/service denied. Applicable withhold amount is applied",
        "509": "Claim/service denied. Services may not be covered for the member due to age",
        "510": "Claim/service denied. Consult plan benefit documents or contact payer regarding dependent eligibility requirements",
        "511": "Reduced/denied for incomplete or invalid lab certification number",
        "512": "Reduced/denied for missing, incomplete, or invalid non-covered charges",
        "513": "Reduced/denied for incomplete or invalid authorization information",
        "514": "Reduced/denied for incomplete or invalid facility identifier",
        "515": "Payment adjusted based on case/care management",
        "516": "Reduced/denied for missing, incomplete, or invalid patient medical record number",
        "517": "Reduced/denied for incomplete or invalid provider commercial registration number",
        "518": "Reduced/denied for missing, incomplete, or invalid identification",
        "519": "Payment based on contracted/legislated fee schedule",
        "520": "Services not covered based on the patient's classification as an outpatient",
        "521": "Payment adjusted based on a Value-Based Reimbursement agreement",
        "522": "Payment adjusted based on a Pay-for-Performance agreement",
        "523": "Reduced/denied for incomplete or invalid identifying information about the rendering or other provider",
        "524": "Reduced/denied for incomplete or invalid information about the assisting surgeon",
        "525": "Reduced/denied for incomplete or invalid information about the referring provider",
        "526": "Services denied as related to a non-covered service",
        "527": "Claim/service denied. Patient is enrolled in a health management program",
        "528": "Claim/service denied. Patient is enrolled in a case management program",
        "529": "Reduced/denied for incomplete or invalid operating provider information",
        "530": "Reduced/denied for incomplete or invalid information about the site of service",
        "531": "Reduced/denied for incomplete or invalid place of treatment information",
        "532": "Reduced/denied for incomplete or invalid ambulance certification information",
        "533": "Reduced/denied for incomplete or invalid durable medical equipment information",
        "534": "Reduced/denied for incomplete or invalid oxygen therapy information",
        "535": "Reduced/denied for incomplete or invalid prosthetics or orthotics information",
        "536": "Reduced/denied for incomplete or invalid diagnosis or treatment date information",
        "537": "Reduced/denied for incomplete or invalid accident information",
        "538": "Reduced/denied for incomplete or invalid information about the occurrence of an accident",
        "539": "Reduced/denied for incomplete or invalid information about the nature of the accident",
        "540": "Reduced/denied for incomplete or invalid information about the location of the accident",
        "541": "Reduced/denied for incomplete or invalid information about medical and other health service providers",
        "542": "Refund/overpayment requested",
        "543": "Reduced/denied for missing, incomplete, or invalid diagnosis/condition information",
        "544": "Reduced/denied for incomplete or invalid spinal manipulation information",
        "545": "Services not covered based on the patient's classification as a partial day patient",
        "546": "Reduced/denied for incomplete or invalid transportation information",
        "547": "Reduced/denied for missing, incomplete, or invalid tooth information",
        "548": "Reduced/denied for missing, incomplete, or invalid oral cavity designation",
        "549": "Reduced/denied for incomplete or invalid orthodontic information",
        "550": "Reduced/denied for incomplete or invalid prosthesis/crown/implant information",
        "551": "Reduced/denied for incomplete or invalid tooth surface information",
        "552": "Payment adjusted for delayed implementation of a regulatory or business mandate",
        "553": "Reduced/denied for incomplete or invalid replacement claim information",
        "554": "Reduced/denied for incomplete or invalid periodontics information",
        "555": "Reduced/denied for incomplete or invalid prosthodontics information",
        "556": "Claim/service denied. Patient is covered under a maintenance program",
        "557": "Reduced/denied for incomplete or invalid orthodontics treatment months count",
        "558": "Reduced/denied for missing, incomplete, or invalid provider address information",
        "559": "Claim/service denied. Patient is enrolled in a direct contract/private contract health plan",
        "560": "Reduced/denied for missing, incomplete, or invalid provider communication numbers",
        "561": "Reduced/denied for missing, incomplete, or invalid Health Care Common Procedure Coding System National codes or Current Procedural Terminology codes",
        "562": "Reduced/denied for incomplete or invalid replacement prosthesis or crown information",
        "563": "Claim/service not covered. Services are not covered when the patient is employed",
        "564": "Claim/service not covered. Services are not covered when the patient is a full-time student",
        "565": "Reduced/denied for incomplete or invalid pricing or repricing information",
        "566": "Reduced/denied for incomplete or invalid Contract Type Code",
        "567": "Not covered. Patient does not reside in the service area required for this type of payment",
        "568": "Reduced/denied for incomplete or invalid purchased service information",
        "569": "Claim/service not covered. Pre-existing condition limitation applies",
        "570": "Reduced/denied for incomplete or invalid billing provider information",
        "571": "Reduced/denied for incomplete or invalid pay-to-provider information",
        "572": "Reduced/denied for incomplete or invalid supervising provider information",
        "573": "Patient not eligible for care coordination/management service from this provider",
        "574": "Services not covered based on the patient's classification as an inpatient",
        "575": "Services provided in a location that is part of an in-network organization, but the location itself is out-of-network",
        "576": "Reduced/denied for incomplete or invalid ambulance patient count information",
        "577": "Reduced/denied for incomplete or invalid ambulance transport reason information",
        "578": "Reduced/denied for missing, incomplete, or invalid service date",
        "579": "Reduced/denied for incomplete or invalid multiple procedure rules",
        "580": "Reduced/denied for incomplete or invalid information about the ordering provider",
        "581": "Claim/service denied. Services are not covered for patients under a coverage category",
        "582": "Patient not eligible for care coordination/management service for this time period",
        "583": "Reduced/denied for missing, incomplete, or invalid provider specialty information",
        "584": "Reduced/denied for incomplete or invalid home oxygen therapy information",
        "585": "Patient not eligible for care coordination/management service on this date of service",
        "586": "Reduced/denied for incomplete or invalid durable medical equipment information",
        "587": "Patient not eligible for this care coordination/management service",
        "588": "Reduced/denied for incomplete or invalid payer identifier",
        "589": "Reduced/denied for missing, incomplete, or invalid admitting diagnosis",
        "590": "Adjustment for patient's primary care provider not being the submitting provider",
        "591": "Reduced/denied for incomplete or invalid coordination of benefits information",
        "592": "Reduced/denied for incomplete or invalid medical assistance category",
        "593": "Payment adjusted for services that are not covered when the patient is in the custody of federal, state or local authorities",
        "594": "Reduced/denied for incomplete or invalid procedure modifier information",
        "595": "Payment adjusted based on a bundled payment agreement",
        "596": "Payment adjusted based on a partial capitation agreement",
        "597": "Patient not eligible for care coordination/management service on this date of service for this specialty/provider type",
        "598": "Reduced/denied for incomplete or invalid principal diagnosis information",
        "599": "Patient not eligible for care coordination/management service on this date of service for this provider",
        "600": "Payment adjusted as all other coverage has not been exhausted",
        "601": "Payment adjusted to correct a previous error",
        "602": "Payment adjusted based on a health equity measure",
        "603": "Reduced/denied for incomplete or invalid home health visit information",
        "604": "Reduced/denied for incomplete or invalid patient discharge status information",
        "605": "Payment adjusted to correct a system error or policy interpretation",
        "606": "Payment adjusted based on a provider agreement",
        "607": "Claim/service denied. Services provided were in excess of plan limits",
        "608": "Payment adjusted to offset previous overpayment",
        "609": "Claim/service not covered. Consult plan documents for coverage information",
        "610": "Payment adjusted for failure to comply with utilization review requirements",
        "611": "Payment adjusted as other coverage was not exhausted",
        "612": "Services provided in inappropriate place of service based on contract",
        "613": "Payment adjusted to reflect the services not included in the per diem rate",
        "614": "Services provided in inappropriate facility based on contract",
        "615": "Reduced/denied for incomplete or invalid certification/recertification information",
        "616": "Claim/service denied. Services provided are for treatment of an excluded condition",
        "617": "Payment adjusted for failure to comply with payer's pre-authorization requirements",
        "618": "Reduced/denied for incomplete or invalid date information",
        "619": "Payment adjusted due to timely filing requirements",
        "620": "Reduced/denied for incomplete or invalid provider certification information",
        "621": "Services not covered. Patient is enrolled in a managed care program",
        "622": "Reduced/denied for incomplete or invalid provider license information",
        "623": "Payment adjusted due to incorrect billing",
        "624": "Payment adjusted based on a participating provider agreement",
        "625": "Payment adjusted based on a risk-sharing agreement",
        "626": "Reduced/denied for incomplete or invalid provider specialty code",
        "627": "Payment adjusted for services rendered during a period of non-compliance",
        "628": "Reduced/denied for incomplete or invalid provider taxonomy code",
        "629": "Claim/service not covered. Services provided are for an excluded condition",
        "630": "Reduced/denied for incomplete or invalid provider classification information",
        "631": "Payment adjusted for failure to comply with the provider agreement",
        "632": "Claim/service not covered. Services provided are for treatment of a non-covered condition",
        "633": "Reduced/denied for incomplete or invalid provider type information",
        "634": "Services not covered. Patient is enrolled in a spend-down program",
        "635": "Payment adjusted based on a Medicaid state demonstration project",
        "636": "Reduced/denied for incomplete or invalid provider licensing information",
        "637": "Payment adjusted based on a coordinated care agreement",
        "638": "Reduced/denied for incomplete or invalid provider NPI information",
        "639": "Payment adjusted based on a Medicare Advantage plan policy",
        "640": "Reduced/denied for incomplete or invalid taxonomy",
        "641": "Payment adjusted based on coordination of benefits with another payer",
        "642": "Claim/service not covered. Services provided are for treatment of an uncovered condition",
        "643": "Payment adjusted for failure to meet medical necessity requirements",
        "644": "Payment adjusted for failure to meet level of care requirements",
        "645": "Payment adjusted for failure to meet utilization requirements",
        "646": "Payment adjusted for failure to meet quality requirements",
        "647": "Payment adjusted for failure to meet documentation requirements",
        "648": "Payment adjusted for failure to meet clinical guidelines",
        "649": "Payment adjusted for failure to meet appropriateness criteria",
        "650": "Payment adjusted for failure to meet eligibility requirements",
        "651": "Reduced/denied for incomplete or invalid provider credentialing information",
        "652": "Payment adjusted for failure to meet coverage requirements",
        "653": "Reduced/denied for incomplete or invalid provider contracting information",
        "654": "Payment adjusted for failure to meet plan requirements",
        "655": "Reduced/denied for incomplete or invalid provider network information",
        "656": "Payment adjusted for failure to meet regulatory requirements",
        "657": "Reduced/denied for incomplete or invalid provider status information",
        "658": "Payment adjusted for failure to meet accreditation requirements",
        "659": "Reduced/denied for incomplete or invalid provider organization information",
        "660": "Payment adjusted for failure to meet certification requirements",
        "661": "Reduced/denied for incomplete or invalid provider affiliation information",
        "662": "Payment adjusted for failure to meet licensure requirements",
        "663": "Reduced/denied for incomplete or invalid provider agreement information",
        "664": "Payment adjusted for failure to meet training requirements",
        "665": "Reduced/denied for incomplete or invalid provider contract information",
        "666": "Payment adjusted for failure to meet education requirements",
        "667": "Reduced/denied for incomplete or invalid provider participation information",
        "668": "Payment adjusted for failure to meet experience requirements",
        "669": "Reduced/denied for incomplete or invalid provider enrollment information",
        "670": "Payment adjusted for failure to meet competency requirements",
        "671": "Reduced/denied for incomplete or invalid provider registration information",
        "672": "Payment adjusted for failure to meet performance requirements",
        "673": "Reduced/denied for incomplete or invalid rendering provider identifier",
        "674": "Payment adjusted for failure to meet compliance requirements",
        "675": "Reduced/denied for incomplete or invalid billing provider identifier",
        "676": "Payment adjusted for failure to meet safety requirements",
        "677": "Reduced/denied for incomplete or invalid pay-to provider identifier",
        "678": "Payment adjusted for failure to meet reporting requirements",
        "679": "Reduced/denied for incomplete or invalid servicing provider identifier",
        "680": "Payment adjusted for failure to meet monitoring requirements",
        "681": "Reduced/denied for incomplete or invalid referring provider identifier",
        "682": "Payment adjusted for failure to meet evaluation requirements",
        "683": "Reduced/denied for incomplete or invalid ordering provider identifier",
        "684": "Payment adjusted for failure to meet outcome requirements",
        "685": "Reduced/denied for incomplete or invalid supervising provider identifier",
        "686": "Payment adjusted for failure to meet process requirements",
        "687": "Reduced/denied for incomplete or invalid attending provider identifier",
        "688": "Payment adjusted for failure to meet structure requirements",
        "689": "Reduced/denied for incomplete or invalid operating provider identifier",
        "690": "Payment adjusted for failure to meet access requirements",
        "691": "Reduced/denied for incomplete or invalid prescribing provider identifier",
        "692": "Payment adjusted for failure to meet availability requirements",
        "693": "Reduced/denied for incomplete or invalid assisting provider identifier",
        "694": "Payment adjusted for failure to meet responsiveness requirements",
        "695": "Reduced/denied for incomplete or invalid primary care provider identifier",
        "696": "Payment adjusted for failure to meet timeliness requirements",
        "697": "Reduced/denied for incomplete or invalid specialist provider identifier",
        "698": "Payment adjusted for failure to meet coordination requirements",
        "699": "Reduced/denied for incomplete or invalid facility provider identifier",
        "700": "Payment adjusted for failure to meet continuity requirements",
        "A0": "Patient refund amount",
        "A1": "Claim/service denied. Consult plan benefit documents/guidelines for information about restrictions for this service",
        "A2": "Contractual adjustment",
        "A3": "Medicare Secondary Payer liability met",
        "A4": "Medicare Claim PPS Capital Day Outlier amount",
        "A5": "Medicare Claim PPS Capital Cost Outlier amount",
        "A6": "Prior hospitalization or 30 day transfer requirement not met",
        "A7": "Presumptive payment adjustment",
        "A8": "Claim/service not covered by this payer/contractor. You must send the claim/service to the correct payer/contractor",
        "B1": "Non-covered visits",
        "B2": "Covered visits",
        "B3": "Covered charges",
        "B4": "Late filing penalty",
        "B5": "Coverage/program guidelines were not met or were exceeded",
        "B6": "This payment is adjusted when performed/billed by this type of provider in this type of facility",
        "B7": "This provider was not certified/eligible to be paid for this procedure/service on this date of service",
        "B8": "Alternative services were available, and should have been utilized",
        "B9": "Patient is enrolled in a Hospice",
        "B10": "Allowed amount has been reduced because a component of the basic procedure/test was paid. The beneficiary is not liable for more than the charge limit for the basic procedure/test",
        "B11": "The claim/service has been transferred to the proper payer/processor for processing. Claim/service not covered by this payer",
        "B12": "Services not documented in patients' medical records",
        "B13": "Previously paid. Payment for this claim/service may have been provided in a previous payment",
        "B14": "Payment denied because only one visit or consultation per physician per day is covered",
        "B15": "Payment adjusted because this service was paid separately at the time the procedure was performed",
        "B16": "Payment for new patient visit is not allowed if a previous related E&M service was provided within a specified time frame prior to the scheduled surgery",
        "B17": "Payment for consult is not allowed if a previous related E&M service was provided within a specified time frame prior to the scheduled surgery",
        "B18": "Procedure code is inconsistent with the intensity of service/level of care provided",
        "B19": "Claim/service has been adjusted based on medical review",
        "B20": "Procedure/service was partially or fully furnished by another provider",
        "B21": "Payment adjusted based on a Risk Adjustment Model",
        "B22": "This payment is adjusted based on the diagnosis",
        "B23": "Procedure billed is not authorized per your Clinical Laboratory Improvement Amendment (CLIA) proficiency test",
        "D1": "Claim/service denied. This service is only covered when the associated service is covered and provided in conjunction with this service",
        "D2": "Claim/service denied. This service is only covered when the associated service is covered and provided separately from this service",
        "D3": "Claim/service denied. The patient is not eligible for this service. See payer's rules for specific information",
        "D4": "Claim/service denied. The patient has been determined to be ineligible for this service. See payer's rules for specific information",
        "D5": "Payment adjusted. Alternative payment methodologies were used for multiple procedures",
        "D6": "This service is not separately reimbursable. Payment for this service is included in the payment for a separate procedure/service",
        "D7": "This service is not separately reimbursable when billed by this provider",
        "D8": "Claim/service not covered by this payer/contractor. You must send the claim/service to the correct payer/contractor. This payer/contractor identified the payer/contractor that you must contact",
        "D9": "Claim/service not covered by this payer/contractor when performed at this facility/location. You must send the claim/service to the payer/contractor that covers services at this facility/location",
        "D10": "Claim/service not covered because the patient is enrolled in a Medicare demonstration program. The patient's enrollment in the demonstration program may be intermittent. If appropriate, resubmit the claim after the patient is no longer enrolled in the demonstration program",
        "D11": "Claim/service not covered. Services provided to patients covered by this payer/contractor must be billed using a different payment methodology. Refer to payer policy and/or state regulations",
        "D12": "Claim/service has been adjusted or denied based on a Demonstration Project",
        "D13": "Payment adjusted because a related service was not provided or was not previously authorized",
        "D14": "Services have been identified as both medically reasonable and necessary, and for research purposes. Payment made from research funds",
        "D15": "Claim/service denied. Services billed are not eligible for payment under the patient's enrollment type. Refer to payer policy for information about restrictions",
        "D16": "Services have been adjusted based on a national payment policy",
        "D17": "Claim/service denied. Additional information needed for correct processing of the claim",
        "D18": "Payment adjusted based on a Clinical Trial/Research Study",
        "D19": "Claim/service denied. Services are not covered when the patient's enrollment is less than 30 days",
        "D20": "Claim/service has been adjusted based on a demonstration project",
        "D21": "This service is not covered when performed during the same session/date/encounter as a previously processed service for the patient",
        "D22": "This service is not covered when performed prior to a previously processed service for the patient",
        "D23": "This service is not covered when performed subsequent to a previously processed service for the patient",
        "P1": "Payment reduced/denied to protect patient's interest",
        "P2": "Not a work related injury/illness and thus not the liability of the workers compensation carrier",
        "P3": "Workers compensation case settled. Patient is responsible for amount of this claim/service through WC 'Medicare set aside arrangement' or other agreement",
        "P4": "Workers compensation medical benefits maximum has been paid",
        "P5": "Based on payer reasonable and customary fees. No maximum allowable defined by legislated fee arrangement",
        "P6": "Based on entitlement to benefits. This payer cannot pay until the patient's personal injury lawsuit is resolved",
        "P7": "The applicable fee schedule/fee database does not contain the billed code. Please resubmit a bill with the appropriate fee schedule/fee database code(s) that best describe the service(s) provided",
        "P8": "Claim is under investigation",
        "P9": "No available or correlating CPT/HCPCS code to describe this service",
        "P10": "Payment reduced to zero due to litigation",
        "P11": "The disposition of the related Property & Casualty claim (injury or illness) is pending due to litigation. To enable proper billing of this claim/service, please complete any necessary litigation or provide proof of law suit settlement/verdict",
        "P12": "Workers compensation jurisdictional fee schedule adjustment",
        "P13": "Payment reduced or denied based on workers compensation jurisdictional regulations or payment policies, use only if no other code is applicable",
        "P14": "The Workers' Compensation claim has been identified as a Medicare Set Aside Arrangement claim",
        "P15": "Workers compensation medical treatment guideline adjustment",
        "P16": "Medical provider not authorized/certified to provide treatment to injured workers in this jurisdiction",
        "P17": "Referral not authorized by attending physician per regulatory requirement",
        "P18": "Procedure is not listed in the jurisdiction fee schedule. An allowance has been made for a comparable service",
        "P19": "Procedure has a relative value of zero in the jurisdiction fee schedule, therefore no payment is due",
        "P20": "Service not paid under workers compensation jurisdictional regulations or payment policies",
        "P21": "Payment denied based on workers compensation medical treatment guidelines",
        "P22": "Payment adjusted based on the Medical Disability Advisor (MDA) treatment guidelines",
        "P23": "Medical provider not authorized/certified to provide services per regulation or contract",
        "W1": "Workers compensation jurisdictional fee schedule adjustment",
        "W2": "Payment reduced or denied based on workers compensation jurisdictional regulations or payment policies, use only if no other code is applicable",
        "W3": "The claim/service has been identified as a duplicate of a previously submitted claim by the Workers Compensation Carrier",
        "W4": "Workers compensation medical treatment guideline adjustment",
        "W5": "Medical provider not authorized/certified to provide treatment to injured workers in this jurisdiction",
        "W6": "Referral not authorized by attending physician per regulatory requirement",
        "W7": "Procedure is not listed in the jurisdiction fee schedule. An allowance has been made for a comparable service",
        "W8": "Procedure has a relative value of zero in the jurisdiction fee schedule, therefore no payment is due",
        "W9": "Service not paid under workers compensation jurisdictional regulations or payment policies",
        "W10": "Payment denied based on workers compensation medical treatment guidelines",
        "W11": "Payment adjusted based on the Medical Disability Advisor (MDA) treatment guidelines",
        "W12": "Medical provider not authorized/certified to provide services per regulation or contract",
        "1P": "Provider",
        "2P": "Billing provider",
        "IL": "Insured/Subscriber/Policyholder",
        "PX": "Referring Provider",
        "TQ": "Third Party",
        "Y1": "Other Payer",
        "Y2": "Other Payer Secondary",
        "Y3": "Other Payer Tertiary"
    }

    # Claim Status Category Codes
    STATUS_MAP = {
        # Finalized Status Codes (F series)
        "F0": "Finalized/No payment - The claim/line has been finalized with no payment.",
        "F1": "Finalized/Payment - The claim/line has been finalized with payment.",
        "F2": "Finalized/Denial - The claim/line has been denied.",
        "F3": "Finalized/Forwarded to other payer - Claim has been forwarded to another payer for processing.",
        "F4": "Finalized/Adjudication with no payment.",
        "F5": "Finalized/Adjudication with payment.",
        "F6": "Finalized/Adjudication denied.",
        "F7": "Finalized/Payment adjustment - Payment has been adjusted from original adjudication.",
        "F8": "Finalized/Zero payment - Claim finalized with zero payment due.",
        "F9": "Finalized/Recoupment - Payment has been recouped or recovered.",

        # Acknowledgement Status Codes (A series)
        "A0": "Acknowledgement/Processed - The claim/line has been processed.",
        "A1": "Acknowledgement/Forwarded - The claim/line has been forwarded to another entity.",
        "A2": "Acknowledgement/Receipt - The claim/line has been received.",
        "A3": "Acknowledgement/Rejected - The claim/line has been rejected.",
        "A4": "Acknowledgement/Accepted - The claim/line has been accepted.",
        "A5": "Acknowledgement/Accepted for processing - The claim/line has been accepted for processing.",
        "A6": "Acknowledgement/Rejected for processing - The claim/line has been rejected for processing.",
        "A7": "Acknowledgement/Pending additional information - The claim/line is pending additional information.",
        "A8": "Acknowledgement/Under review - The claim/line is under review.",
        "A9": "Acknowledgement/More information to follow - The claim/line will have more information to follow.",
        "A10": "Acknowledgement/Deferred - The claim/line has been deferred.",
        "A11": "Acknowledgement/Preliminary adjudication - The claim/line is pending preliminary adjudication.",
        "A12": "Acknowledgement/Duplicate - Claim has been identified as a duplicate.",
        "A13": "Acknowledgement/Split claim - Claim has been split into multiple claims for processing.",

        # Pending Status Codes (P series)
        "P0": "Pending/No action taken - The claim/line is pending with no action taken.",
        "P1": "Pending/Additional information required - The claim/line is pending additional information from the provider or other entity.",
        "P2": "Pending/Under review - The claim/line is pending review by the payer.",
        "P3": "Pending/More information to follow - The claim/line is pending more information to follow from another source.",
        "P4": "Pending/Deferred - The claim/line is pending deferral to a later date.",
        "P5": "Pending/Preliminary adjudication - The claim/line is pending preliminary adjudication.",
        "P6": "Pending/Investigation - The claim/line is pending investigation for potential issues.",
        "P7": "Pending/Coordination of benefits - The claim/line is pending coordination of benefits with other payers.",
        "P8": "Pending/Medical review - The claim/line is pending medical review for necessity or appropriateness.",
        "P9": "Pending/Utilization review - The claim/line is pending utilization review for compliance with guidelines.",
        "P10": "Pending/Authorization required - The claim/line is pending authorization from the payer or other entity.",
        "P11": "Pending/Eligibility verification - The claim/line is pending verification of patient eligibility.",
        "P12": "Pending/Claim hold - The claim/line is on hold for further review or action.",
        "P13": "Pending/Provider review - The claim/line is pending review by the provider for accuracy or completeness.",
        "P14": "Pending/Patient follow-up - The claim/line is pending follow-up with the patient for additional information.",
        "P15": "Pending/Third-party review - The claim/line is pending review by a third party for additional assessment.",
        "P16": "Pending/Legal review - The claim/line is pending legal review for compliance with regulations or policies.",
        "P17": "Pending/Fraud investigation - The claim/line is pending investigation for potential fraud or abuse.",
        "P18": "Pending/Payment review - The claim/line is pending review for payment accuracy or adjustments.",
        "P19": "Pending/Other - The claim/line is pending for other unspecified reasons.",
        "P20": "Pending/Administrative review - The claim/line is pending administrative review for processing or handling.",
        "P21": "Pending/Technical review - The claim/line is pending technical review for system or data issues.",
        "P22": "Pending/Policy review - The claim/line is pending review for policy compliance or updates.",
        "P23": "Pending/Benefit verification - The claim/line is pending verification of patient benefits or coverage.",
        "P24": "Pending/Service review - The claim/line is pending review of the services provided for accuracy or necessity.",
        "P25": "Pending/Documentation review - The claim/line is pending review of submitted documentation for completeness or validity.",
        "P26": "Pending/Coordination with other claims - The claim/line is pending coordination with other related claims for processing.",
        "P27": "Pending/Review by external entity - The claim/line is pending review by an external entity for additional assessment or validation.",
        "P28": "Pending/Review by internal department - The claim/line is pending review by an internal department for further evaluation or action.",
        "P29": "Pending/Review by clinical team - The claim/line is pending review by the clinical team for medical necessity or appropriateness.",
        "P30": "Pending/Review by billing department - The claim/line is pending review by the billing department for accuracy or completeness.",
        "P31": "Pending/Review by customer service - The claim/line is pending review by customer service for resolution or assistance.",
        "P32": "Pending/Review by management - The claim/line is pending review by management for oversight or decision-making.",
        "P33": "Pending/Review by quality assurance - The claim/line is pending review by quality assurance for compliance or standards.",
        "P34": "Pending/Review by audit team - The claim/line is pending review by the audit team for verification or validation.",
        "P35": "Pending/Review by external auditor - The claim/line is pending review by an external auditor for independent assessment or validation.",
        "P36": "Pending/Waiting for patient information - Additional information needed from patient.",
        "P37": "Pending/Waiting for prior payer response - Waiting for coordination of benefits information from another payer.",
        "P38": "Pending/Price review - Pricing or fee schedule verification in progress.",
        "P39": "Pending/Timely filing review - Review of claim submission timeliness.",
        "P40": "Pending/Duplicate check - Verifying claim is not a duplicate submission.",

        # Rejected Status Codes (R series)
        "R0": "Rejected/Invalid information - Claim rejected due to invalid information.",
        "R1": "Rejected/Missing information - Claim rejected due to missing required information.",
        "R2": "Rejected/Duplicate claim - Claim rejected as duplicate.",
        "R3": "Rejected/Invalid provider - Provider information is invalid or not recognized.",
        "R4": "Rejected/Invalid member - Member/patient information is invalid or not found.",
        "R5": "Rejected/Invalid procedure code - Procedure code is invalid or not covered.",
        "R6": "Rejected/Invalid diagnosis code - Diagnosis code is invalid.",
        "R7": "Rejected/Eligibility terminated - Patient coverage has terminated.",
        "R8": "Rejected/Timely filing - Claim not filed within required timeframe.",
        "R9": "Rejected/Authorization required - Prior authorization was required but not obtained.",
        "R10": "Rejected/Invalid place of service - Place of service code is invalid.",

        # Suspended Status Codes (S series)
        "S0": "Suspended/General - Claim is suspended for review.",
        "S1": "Suspended/Additional development - Requires additional information or development.",
        "S2": "Suspended/Medical review - Suspended for medical necessity review.",
        "S3": "Suspended/Fraud review - Suspended for potential fraud investigation.",
        "S4": "Suspended/Pricing review - Suspended for pricing verification.",
        "S5": "Suspended/Coordination of benefits - Suspended for COB determination.",

        # Returned Status Codes (T series)
        "T0": "Returned/Unprocessable - Claim returned as unprocessable.",
        "T1": "Returned/Invalid format - Claim returned due to invalid format.",
        "T2": "Returned/Missing attachment - Required attachment is missing.",
        "T3": "Returned/To provider - Claim returned to provider for correction.",

        # Voided Status Codes (V series)
        "V0": "Voided - Claim has been voided.",
        "V1": "Voided/Replaced - Claim voided and replaced by corrected claim.",
        "V2": "Voided/Duplicate - Claim voided as duplicate.",

        # In Process Status Codes (I series)
        "I0": "In process - Claim is currently being processed.",
        "I1": "In process/Pricing - Pricing determination in progress.",
        "I2": "In process/Adjudication - Claim adjudication in progress.",
        "I3": "In process/Payment calculation - Payment amount being calculated.",

        # Corrected Status Codes (C series)
        "C0": "Corrected/Replacement received - Corrected claim has been received.",
        "C1": "Corrected/Void and replace - Original claim voided, replacement processing.",
        "C2": "Corrected/Adjustment - Claim adjustment in process.",

        # Appeal Status Codes (E series)
        "E0": "Appeal/Received - Appeal has been received.",
        "E1": "Appeal/Under review - Appeal is under review.",
        "E2": "Appeal/Approved - Appeal has been approved.",
        "E3": "Appeal/Denied - Appeal has been denied.",
        "E4": "Appeal/Partially approved - Appeal partially approved.",

        # Other Standard Status Codes
        "1": "For more detailed information, see remittance advice.",
        "2": "More detailed information in letter.",
        "3": "Claim has been adjudicated and is awaiting payment cycle.",
        "4": "This is a subsequent request for information from the original request.",
        "5": "Claim has been forwarded to entity.",
        "6": "Entity must contact member to obtain missing information.",
        "7": "Claim may be reconsidered at a future date.",
        "8": "No payment will be made for this claim.",
        "9": "Final status - claim paid.",
        "10": "Final status - claim denied.",
        "11": "Final status - claim pending.",
        "12": "Waiting for patient to provide information.",
        "13": "Claim has been paid, but reconsideration may change payment.",
        "14": "Claim has been denied, but reconsideration or appeal may change status.",
        "15": "Claim has been received, but has not been processed.",
        "16": "Claim/encounter has been adjudicated - no payment required.",
        "17": "Claim/line forwarded to another payer for processing.",
        "18": "Claim pending for other insurance payment.",
        "19": "Claim suspended for manual review.",
        "20": "Claim pended for pricing.",
        "21": "Claim pended for bundling.",
        "22": "Claim pended for COB.",
        "23": "Claim pended for medical review.",
        "24": "Claim pended for fraud review.",
        "25": "Claim closed with zero payment."
    }

    @classmethod
    def get_reason_code(cls, reason_code):
        return cls.REASON_MAP.get(reason_code, "")

    @classmethod
    def get_status_code(cls, status_code):
        return cls.STATUS_MAP.get(status_code, "")

